### ISSUE TITLE
IOS - misplaced cursor 

### ISSUE THREAD

**Issue by padejar** [adar2378/pin_code_fields#20] opened 2019-11-28 10:28 UTC
Hi, my QA team found that there's a misplaced cursor on the iOS iPhone 7 device running ios 13. 

![6b53c2c4-beee-4517-a37f-f0a84c4876ba](https://user-images.githubusercontent.com/16450589/69798403-ce166f00-1203-11ea-94c3-9b8a29065d9a.png)

Here's my implementation

```
return new Scaffold(
      key: _otpKey,
      backgroundColor: Colors.white,
      appBar: CustomAppBar(title: AppLocalization.of(context).verificationNumber, showBackButton: false),
      body: _isResendLoading
          ? LoadingIndicator()
          : Container(
              padding: EdgeInsets.fromLTRB(40.0, 20.0, 40.0, 20.0),
              child: new Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  Container(
                    margin: EdgeInsets.only(top: 15.0),
                  ),
                  RichText(
                    text: TextSpan(
                      style: TextStyle(color: CustomColors.mainColor()),
                      children: <TextSpan>[
                        TextSpan(text: AppLocalization.of(context).enterTheCode + ' '),
                        TextSpan(
                            text: phoneNumber + '.',
                            style: TextStyle(fontWeight: FontWeight.bold)),
                        TextSpan(text: ' ' + AppLocalization.of(context).itsOnlyValid),
                      ],
                    ),
                  ),
                  _buildForm(context),
                  Expanded(
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: _buildBottom(context),
                    ),
                  ),
                ],
              ),
            ),
    );
  }

  Widget _buildForm(context) {
    return new Form(
      key: otpFormKey,
      child: new Container(
        width: 250.0,
        child: new Column(
          children: <Widget>[
            PinCodeTextField(
              length: 4,
              obsecureText: false,
              shape: PinCodeFieldShape.circle,
              borderRadius: BorderRadius.circular(20.0),
              backgroundColor: Colors.white,
              textInputType: TextInputType.number,
              currentText: (value) {
                setState(() {
                  _otpCode = value;
                });

                if (value.length == 4) {
                  verifyOtp();
                  return;
                }
              },
              borderWidth: 2.0,
              activeColor: Color.fromRGBO(90, 96, 117, 1),
              inactiveColor: Color.fromRGBO(205, 205, 205, 1),
              fieldHeight: 100.0,
              fieldWidth: 50.0,
            )
          ],
        ),
      ),
    );
  }
```

**Comment by adar2378** [comment] 2019-11-28 10:41
Please update the package to the latest version and see if the bug still persists.
`pin_code_fields: ^2.2.1+2`

**Comment by adar2378** [comment] 2019-11-28 10:42
Duplicate of #5

**Comment by adar2378** [comment] 2019-11-29 09:22
I think updating to the latest version of this package will solve it.

**Comment by Jayant-BL** [comment] 2019-12-16 08:42
Same issue after update on 
 shape: PinCodeFieldShape.underline, 

using latest version pin_code_fields 2.3.0+2

**Comment by adar2378** [comment] 2019-12-16 08:44
Could you give me the sample code that you're using along with the screenshot? Thanks

**Comment by Jayant-BL** [comment] 2019-12-17 05:29
` PinCodeTextField(
                    length: 6,
                    obsecureText: false,
                    animationType: AnimationType.fade,
                    shape: PinCodeFieldShape.underline,
                    animationDuration: Duration(milliseconds: 300),
                    borderRadius: BorderRadius.circular(5),
                    fieldHeight: height50,
                    fieldWidth: width40,
                    onChanged: bloc.changeOTP
                  )`

![WhatsApp Image 2019-12-17 at 10 54 41 AM](https://user-images.githubusercontent.com/56577731/70967417-38605800-20bc-11ea-8972-ec732ae23703.jpeg)
![WhatsApp Image 2019-12-17 at 10 54 41 AM(1)](https://user-images.githubusercontent.com/56577731/70967429-401ffc80-20bc-11ea-9565-8d9cf5310ce2.jpeg)

**Comment by adar2378** [comment] 2019-12-17 05:40
Thanks for your feedback. Did you change any colors anywhere? Because I've used the same code on the example app and the cursor is not showing here. Normally the cursor color should match the background color and it blends in. But if you put 100% transparent background then it may show. It is an issue with transparent color that I can be solved by setting the showCursor flag in the hidden textfield widget but that prevents the UI from scrolling up if your pin code field is at the lower part of the screen. 



<a href="https://ibb.co/nsVTzGv"><img src="https://i.ibb.co/4ZDcPqG/Screenshot-1576560978.png" alt="Screenshot-1576560978" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>gif upload</a><br />

**Comment by adar2378** [comment] 2019-12-17 05:47
okay, it is not related to 100% transparent. The cursor shows at any transparency.

**Comment by adar2378** [comment] 2019-12-17 06:17
Please update to the latest version to see if you still have it.
f4543b6c17d0236618150492f8788c038db26869

**Comment by Jayant-BL** [comment] 2019-12-23 06:29
Thanks

**Closed** 2019-12-25 03:23 UTC
